#encoding: utf-8


#n = Node.create(:name => "国学", :alias => "guoxue")
#Category.create(:node_id => n.id, :name => "先秦", :summary => "公元前1046年至公元前204年")
#Category.create(:node_id => n.id, :name => "秦汉", :summary => "公元前203年至公元265年")
#Category.create(:node_id => n.id, :name => "两晋南北朝", :summary => "公元266年至公元589年")
#Category.create(:node_id => n.id, :name => "隋唐", :summary => "公元590年至公元959年")
#Category.create(:node_id => n.id, :name => "宋辽金", :summary => "公元960年至公元1278年")
#Category.create(:node_id => n.id, :name => "元代", :summary => "公元1279年至公元1369年")
#Category.create(:node_id => n.id, :name => "明清", :summary => "公元1370年至公元1911年")
#Category.create(:node_id => n.id, :name => "现当代", :summary => "公元1912年至公元2000年")
#Category.create(:node_id => n.id, :name => "通论", :summary => "-")
#
#n = Node.create(:name => "中医", :alias => "zhongyi")
#Category.create(:node_id => n.id, :name => "经典", :summary => "经典")
#Category.create(:node_id => n.id, :name => "中医学基础", :summary => "中医学基础")
#Category.create(:node_id => n.id, :name => "中药学", :summary => "中药学")
#Category.create(:node_id => n.id, :name => "方剂学", :summary => "方剂学")
#Category.create(:node_id => n.id, :name => "中医临床学", :summary => "中医临床学")
#Category.create(:node_id => n.id, :name => "中医内科学", :summary => "中医内科学")
#Category.create(:node_id => n.id, :name => "中医外科学", :summary => "中医外科学")
#Category.create(:node_id => n.id, :name => "中医妇科学", :summary => "中医妇科学")
#Category.create(:node_id => n.id, :name => "中医儿科学", :summary => "中医儿科学")
#Category.create(:node_id => n.id, :name => "中医骨伤科学", :summary => "中医骨伤科学")
#Category.create(:node_id => n.id, :name => "中医肿瘤科", :summary => "中医肿瘤科")
#Category.create(:node_id => n.id, :name => "中医皮肤科", :summary => "中医皮肤科")
#Category.create(:node_id => n.id, :name => "中医五官科", :summary => "中医五官科")
#Category.create(:node_id => n.id, :name => "中医养生美容学", :summary => "中医养生美容学")
#Category.create(:node_id => n.id, :name => "中医其他学科", :summary => "中医其他学科")

NewsCategory.destroy_all

nc = NewsCategory.create(:name => "新手指南")
NewsTopic.create(:news_category_id => nc.id, :title => "购物流程", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "现金券规则", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "红包规则", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "积分制度", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "会员制度", :content => "")
nc = NewsCategory.create(:name => "支付方式")
NewsTopic.create(:news_category_id => nc.id, :title => "在线支付", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "货到付款", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "汇款支付", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "发票制度说明", :content => "")
nc = NewsCategory.create(:name => "配送说明")
NewsTopic.create(:news_category_id => nc.id, :title => "配送收费标准", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "货到付款地区", :content => "")
nc = NewsCategory.create(:name => "售后服务")
NewsTopic.create(:news_category_id => nc.id, :title => "退换货政策", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "退换货流程", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "问题登记", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "投诉与建议", :content => "")
nc = NewsCategory.create(:name => "帮助中心")
NewsTopic.create(:news_category_id => nc.id, :title => "常见问题", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "忘记密码", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "订单查询", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "联系我们", :content => "")
nc = NewsCategory.create(:name => "关于经典书社")
NewsTopic.create(:news_category_id => nc.id, :title => "经典书社简介", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "成为供货商", :content => "")
NewsTopic.create(:news_category_id => nc.id, :title => "团购批发", :content => "")


#ProductProp.create(:zh => "出版时间", :name => "pub_date")
#ProductProp.create(:zh => "开本", :name => "size")
#ProductProp.create(:zh => "页数", :name => "pages")

